version: '3.4'

networks:
  dev:
    driver: bridge

services:
  swifthelperbackend:
    image: swifthelpercontainer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:81
      - ASPNETCORE_HTTPS_PORT=5000
    ports:
      - 81:81
      - 5000:5000
    depends_on:
      - "swifthelperdb"
    networks:
      - dev

  swifthelperdb:
    image: postgres:latest
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    container_name: swifthelperdb
    environment:
      - POSTGRES_USER=swifthelper123
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - dev

volumes:
  db_volume: